### ISSUE TITLE
Control "Bound object frame" causes the process to fail

### ISSUE THREAD

**Issue by JoePlant** [JoePlant/access-analysis#6]
The control type "Bound object frame" is not handled correctly.

**Comment by JoePlant** [comment]
Error occurred while executing stylesheet 'Stylesheets\extract-link-data.xslt'.

System.Xml.Xsl.XsltException: 'Bound object frame' is an invalid QName.
   at System.Xml.Xsl.XsltOld.PrefixQName.ParseQualifiedName(String qname, String& prefix, String& local)
   at System.Xml.Xsl.XsltOld.PrefixQName.SetQName(String qname)
   at System.Xml.Xsl.XsltOld.ElementAction.CreateElementQName(String name, String nsUri, InputScopeManager manager)
   at System.Xml.Xsl.XsltOld.ElementAction.Execute(Processor processor, ActionFrame frame)
   at System.Xml.Xsl.XsltOld.ActionFrame.Execute(Processor processor)
   at System.Xml.Xsl.XsltOld.Processor.Execute()
   at System.Xml.Xsl.XsltOld.Processor.Execute(Stream stream)
   at System.Xml.Xsl.XslTransform.Transform(XPathNavigator input, XsltArgumentList args, Stream output, XmlResolver resolver)
   at System.Xml.Xsl.XslTransform.Transform(IXPathNavigable input, XsltArgumentList args, Stream output)
   at GotDotNet.Exslt.ExsltTransform.Transform(IXPathNavigable ixn, XsltArgumentList arglist, Stream stream)
   at NXslt.NXslt.Process()

**Comment by JoePlant** [comment]
Fixed issue #6
